= Bash isn't bad--you're bad _at_ it.
:source-highlighter:     pygments
:pygments-style:         algol_nu
:pygments-linenums-mode: table
:toc:                    preamble
:toclevels:              3

A provocative title, and intentionally so.

Bash has a reputation for being unsafe, ill-suited to complex tasks, and oft badly written.
These problems are not all inherent to the language.
Most are caused by the user.


== The thesis
> You can write a bad program in any language.

Why then do people seem to write bad bash more often?

The majority of errors present in bash scripts are easily avoidable.
Most importantly, they're avoidable without added effort or complexity.

It is my contention that good bash is equally easy to write.
You just need to know how.


== The problems
=== Lack of quoted variables
.What
Unquoted variables may either glob match unintended files/directories, or expand to multiple '`words`'.

.General rule
Quote all variables all the time.

.Examples
[source,bash,linenums]
----
# Don't do this.
path='/Application Support/something/else'
mkdir $path

# The above is equivalent to calling:
mkdir '/Application'  'Support/something/else'

# Do this.
mkdir "$path"


# Don't do this.
string="D*"
echo $string

# Expected result :  D*
# Actual result   :  Desktop Downloads Documents

# Do this.
echo "$string"
----


=== Lack of comments
.What
Comments are more necessary in bash, due to...

_Higher level of possible complexity._ +
Bash's syntax may occasionally border on "`executable line noise`", particularly with a heavy use of pipelines.
One must not only be familiar with bash itself, but also common command line tools like `awk`, `sed`, `cut`, `tr`, etc..

_Less time spent in the code._ +
It is less likely for someone to be immersed in the same bash file for an extended period of time.
It's written, and much later unearthed, probably by a different developer.
Anything complex that "`made sense at the time`" won't later.

Tell me what this does off the top of your head:

[source]
----
ARRAY=("${ARRAY[@]::${#ARRAY[@]}-1}")
----

.General rule
Comment your code, particularly blocks that are dense and/or weird.

.Example
[source,bash,linenums]
----
# This is equivalent to `array.pop()`. An array slice from 0 -> length-1.
ARRAY=("${ARRAY[@]::${#ARRAY[@]}-1}")
----


=== Using legacy tests & command substitution
.What
Single brackets for test, `[\...]`, and backticks to capture command output, `{backtick}\...{backtick}`, have been deprecated.

.General rule
Use `[[ \... ]]` for tests, and `$( \... )` for capturing output.

.Examples
[source,bash,linenums]
----
# Don't use single brackets for tests.
if [ -n var ]

# Use double brackets. It allows for and regex and logical and/or in the test.
if [[ $var1 =~ <regex_pattern>           ]] ; then ... fi
if [[ $var1 == cond1  &&  $var2 == cond2 ]] ; then ... fi

# This particularly can help with a lot of conditions that would be otherwise
# tricky to format:
if [[ $var1 == cond1 &&
      $var2 == cond2 &&
      $var3 == cond3 ]]
then
   ...
fi


# Don't use backticks to capture command output.
output=`cmd`

# Use $(...), it's nestable and has a significantly more clear start & stop
# token.
output=$(cmd)
progdir=$( cd $(dirname "${BASH_SOURCE[@]}") ; pwd )
----


=== Lack of native arithmetic
.What
Bash can natively perform arithmetic.
It simplifies loops and variable assignment.

.General rule
If you don't need floats, there's no reason to pipe to `bc`, or `awk` trickery.
Use double parens for arithmetic expressions.

.Examples
[source,bash,linenums]
----
# Assignment.
(( a=0, b=a+1 ))

echo "a: ${a}, b: ${b}"
# a: 0, b: 1


# C-style loop.
for (( idx=0; idx<10; ++idx )) ; do
   echo "$idx"
done

# Double parens as a conditional.
while ((idx < 10)) ; do
   echo "$idx"
   (( ++idx ))
done
----

WARNING: Expressions in double parens that evaluate to `0` have a return status of `1`.
         If you've included a `set -e` at the top of your script, `\(( 0 ))` will cause a very confusing and silent exit.


=== Lack of parameter expansion
.What
Often one needs to pass in configuration variables from the environment.
Handling default values can tricky, and add complexity.

.General rule
Setting variable defaults through parameter expansion <<spe>> can help make code more clear.

.Simple parameter expansion
[cols='1,3']
|===
| Variable | Definition

| `${VAR:-value}`
| If `$VAR` is empty, expand to `value` instead

| `${VAR=value}`
| If `$VAR` is empty, set the variable `VAR` to the string `value`
|===

.Examples
[source,bash,linenums]
----
# Replace the value of $VERBOSE (if unset) with the string `not set`.
echo "Verbosity set to: ${VERBOSE:-not set}"

# The colon command will evaluate its arguments then return with a 0-status.
# This *sets* a variable if not already defined.
: ${VERBOSE=0}
----


=== Lack of using arrays
.What
Bash has arrays.
Oftentimes programmers that would reach for an array in any other language won't in bash.

.General rule
Use arrays to reduce repetition, and simplify refactoring.

NOTE: Indexed arrays are present in Bash 3 (the default on macOS).
      Associative arrays (dicts, hash maps, whatever you call them) require Bash 4+.

.Example
[source,bash,linenums]
----
# Arrays can be used to pass function arguments without needing to escape newlines.
# Escaping newlines is fragile, and should be avoided at all costs.
#
# Don't do this.
cmd --arg1 --arg2 --yet-another-arg \
    --this-flag-is-really-long \
    --this-takes-a-path ./path/to/a/file/thats/long \
    --verbose

# Do this.
params=(
   --arg1
   --arg2
   --yet-another-arg
   --this-flag-is-really-long
   --this-takes-a-path ./path/to/a/file/thats/long
   --verbose
)
cmd "${params[@]}"


# Or when creating a bunch of directories:
dirs=(
   /path/to/dir1
   /path/to/dir2
   /path/to/dir3
   /path/to/dir4
)

mkdir -p "${dirs[@]}"
----


=== Silly uses of eval
.What
Sometimes `eval` is the right tool for the job.
More often than not there are safer alternatives available.

.General rule
You can replace 95% of `eval` statements with a nameref.

.Example
[source,bash,linenums]
----
declare -- foo='this'
declare -n bar='foo'    # bar points to variable `foo`

echo "$foo"             # 'this'
echo "$bar"             # 'this'

declare -- bar='that'
echo "$foo"             # 'that'
echo "$bar"             # 'that'
----

Changing `bar` becomes equivalent to changing `foo` itself.
But why would we need to use such a thing?

.The situation
We need to make an API call and pass a secret depending on our environment (dev, preprod, prod).
The script takes a parameter for the environment we're in, and should load the corresponding secret.

.Environment
[source,bash,linenums]
----
DEV_SECRET='xxx'
PREPROD_SECRET='yyy'
PROD_SECRET='zzz'
----

.Script
[source,bash,bash]
----
# Pass in variable if we're in dev/prod/preprod.
env="$1"

# Create nameref to the environment variable, calling .upper(env) so it matches
# the case of the variable.
declare -n secret="${env^^}_SECRET"

# Test if the variable is defined.
if [[ -z $secret ]] ; then
   echo "No secret exists for environment: $env" 1>&2
   exit 1
fi

# $secret now references either $DEV_SECRET, $PRE_PROD, or $PROD_SECRET,
# depending on user input.
api --token "$secret"
----


=== No tests
.What
Bash scripts should be tested too.
There are edge cases that are easy to miss, with potentially disasterous consequences.

.General rule
Always use `shellcheck` <<shck>>.
If you value your time, and don't like troubleshooting, use `bats` <<bats>>.

==== ShellCheck
ShellCheck is a static analysis tool for shell scripts.
It runs extremely quickly, and identifies common errors.
You have literally no reason not to use it on every script.

../script.sh
[source,bash,linenums]
----
#!/bin/bash

function foo {
   local bar=$1
   return 1
}

if ! foo ; then
   echo "Foo failed I guess." 1>&2
fi
----

.Example output
[source]
----
$ shellcheck script.sh

In script.sh line 3:
function foo {
^-- SC2120 (warning): foo references arguments, but none are ever passed.


In script.sh line 4:
   local bar=$1
         ^-^ SC2034 (warning): bar appears unused. Verify use (or export if used externally).


In script.sh line 8:
if ! foo ; then
     ^-^ SC2119 (info): Use foo "$@" if function's $1 should mean script's $1.

For more information:
  https://www.shellcheck.net/wiki/SC2034 -- bar appears unused. Verify use (o...
  https://www.shellcheck.net/wiki/SC2120 -- foo references arguments, but non...
  https://www.shellcheck.net/wiki/SC2119 -- Use foo "$@" if function's $1 sho...
----


==== BATS
BATS is a unit testing framework for Bash.
Setup is quick.
Test are written in native bash.
Here is a brief example.

../calc.sh
[source,bash,linenums]
----
function add {
   echo "$(( $1 + $2 ))"
}
----

../test.bats
[source,bash,linenums]
----
@test "1 + 1 = 2" {
   source "${BATS_TEST_DIRNAME}/calc.sh"
   run add 1 1

   # Exit status saved in $status variable.
   [[ $status -eq 0 ]]

   # stdout is saved in $output. Should be equal to the sum of the two args.
   [[ $output -eq 2 ]]
}
----

.Run tests!
[source,bash]
----
$ bats test.bats
----


[bibliography]
== References

* [[[spe,  0]]] https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html[Shell Parameter Expansion]
* [[[shck, 1]]] https://www.shellcheck.net/[ShellCheck]
* [[[bats, 2]]] https://bats-core.readthedocs.io/en/stable/[bats-core]
